Adicionando diagrama de componentes e a descrição de cada componente.
RodrigoEC/arqsoft-blog pull request #1
Opened 2022-06-17 18:06 UTC by dnlgomesl

2022-06-19 13:21 UTC, RodrigoEC requested changes
Ta top, só pedi algumas modificações

2022-06-19 13:21 UTC, RodrigoEC commented on content/posts/hoco.md
> +**Questions Controller e Organization Controller:** São REST Controllers do Flask que fazem o controle sobre a sessão de perguntas e de organização do HoCo, respectivamente, pois é possível que o usu
```suggestion
**Questions Controller e Organization Controller:** São REST Controllers do Flask que fazem o controle sobre a sessão de perguntas e de organização do HoCo, respectivamente, pois é possível que o usuário administrador cadastre dúvidas e suas respostas e organizações e comunidades existentes na graduação no HoCo, esses componetes fazem uso respectivamente dos componetes Questions Modells e Organization Modells. Ambos não precisam de login;
```

2022-06-19 13:21 UTC, RodrigoEC commented on content/posts/hoco.md
> +**Questions Modells e Organization Modells:** São componetes que fazem a conexão com o Banco de Dados, fazendo leitura e/ou escrita dos dados no mesmo;
```suggestion
**Questions Models e Organization Models:** São componetes que fazem a conexão com o Banco de Dados, fazendo leitura e/ou escrita dos dados no mesmo;
```

2022-06-19 13:21 UTC, RodrigoEC commented on content/posts/hoco.md
> +**Login Controller:** Esse componente é um REST Controller do Flask que faz o controle da sessão de login, é responsável por realizar o login e logout do usuário e a restauração da senha do usuário,
```suggestion
**Login Controller:** Esse componente é um REST Controller do Flask que faz o controle da sessão de login, é responsável por realizar o login e logout do usuário e a restauração da senha do usuário, fazendo uso do componente Security Component;
```

2022-06-19 13:21 UTC, RodrigoEC commented on content/posts/hoco.md
> +**User Modells:** É o componenente que faz a conexão com o Banco de Dados, fazendo a leitura e escrita dos dados no mesmo;
```suggestion
**User Models:** É o componenente que faz a conexão com o Banco de Dados, fazendo a leitura e escrita dos dados no mesmo;
```

2022-06-19 13:21 UTC, RodrigoEC commented on content/posts/hoco.md
> +**User Controller:** É um REST Controller do Flask que provê todas as funcionalidades referentes à um usuário em específico (por isso faz uso do Security Component, pois é necessário que o usuário es
```suggestion
**User Controller:** É um REST Controller do Flask que provê todas as funcionalidades referentes à um usuário em específico, por isso faz uso do Security Component, pois é necessário que o usuário esteja logada para que a pessoa possa acessar funcionalidades especificas, como cadastro de atividades (Rota de acessoa 
 dúvidas e respostas, organizações e cadastro do usuário são públicas para qualquer pessoa acessar sem login), como o cadastro do usuário (não precisa de login), exclusão de conta, cadastro de atividades, exclusão de atividade, edição de perfil, aprovar atividade (precisa que o usuário tenha mais permissões, não permitindo que um aluno aprove atividades);
```

2022-06-19 17:26 UTC, LeandraOS reviewed
Se o print do diagrama puder ser mais focado nos componentes ficará ainda mais interessante. Porque a imagem atual tem muita área em branco, fazendo com que o digrama fique menor e menos visível.

2022-06-19 17:26 UTC, LeandraOS commented on content/posts/hoco.md
> +**Questions Controller e Organization Controller:** São REST Controllers do Flask que fazem o controle sobre a sessão de perguntas e de organização do HoCo, respectivamente, pois é possível que o usu
alterar componetes para **componentes**

2022-06-19 17:26 UTC, LeandraOS commented on content/posts/hoco.md
> +**Questions Models e Organization Models:** São componetes que fazem a conexão com o Banco de Dados, fazendo leitura e/ou escrita dos dados no mesmo;
alterar componetes para componentes

2022-06-19 17:26 UTC, LeandraOS commented on content/posts/hoco.md
> +**Atividade Service:** É o componente responsável por prover todas as funcionalidades referentes às atividades, como cadastro, cálculo de créditos, recuperação das atividades e suas informações. Esse
alterar tambem por **também**

2022-06-19 20:50 UTC, dnlgomesl commented
> Se o print do diagrama puder ser mais focado nos componentes ficará ainda mais interessante. Porque a imagem atual tem muita área em branco, fazendo com que o digrama fique menor e menos visível.

Certo, tentarei diminui mais os espaçamentos.

2022-06-20 01:35 UTC, dnlgomesl commented
> Se o print do diagrama puder ser mais focado nos componentes ficará ainda mais interessante. Porque a imagem atual tem muita área em branco, fazendo com que o digrama fique menor e menos visível.

Nfoi um print e sim eu o exportei do site onde fiz o diagrama. Acredito que diminuindo os espaçamentos fique meio confuso.

2022-06-20 22:42 UTC, merged