Adicionando visão de informação com diagrama de máquina de estados
RodrigoEC/arqsoft-blog pull request #2
Opened 2022-06-18 15:11 UTC by icaro-chagas

2022-06-19 13:27 UTC, RodrigoEC requested changes
Falta so uma coisinha, a atividade pode ser rejeitada mesmo, não somente pedida para edição

2022-06-19 13:29 UTC, RodrigoEC requested changes

2022-06-19 13:29 UTC, RodrigoEC commented on content/posts/hoco.md
> +A máquina de estados a seguir explicita o ciclo de vida do processo de dispensa de horas complementares proposto pelo HoCo. Para tal, inicialmente cadastra-se atividades do aluno informando o nome da
```suggestion
A máquina de estados a seguir explicita o ciclo de vida do processo de dispensa de horas complementares proposto pelo HoCo. Para tal, inicialmente cadastra-se atividades do aluno informando o nome da atividade, os créditos obtidos na atividade, as horas equivalentes a atividade, e a categoria da atividade (tais dados são persistidos em um banco de dados). Caso algum dado necessite de alteração, efetua-se a edição dos dados (um ou mais campos de interesse).

Em seguida, para comprovar a validade das informações fornecidas, os arquivos comprovatórios de cada atividade são carregados e enviados para a coordenação do curso para que a validação dos dados possa ser efetuada. 

Caso as informações entre os dados e os arquivos sejam compatíveis o processo de dispensa de horas é efetuado. Caso contrário, o usuário é informado de uma incompatibilidade entre as informações, e o ciclo deve seguir novamente a partir do estado de edição.
```

2022-06-20 12:56 UTC, icaro-chagas commented on content/posts/hoco.md
> +A máquina de estados a seguir explicita o ciclo de vida do processo de dispensa de horas complementares proposto pelo HoCo. Para tal, inicialmente cadastra-se atividades do aluno informando o nome da
Alterado!

2022-06-20 22:47 UTC, LeandraOS approved these changes

2022-06-20 22:47 UTC, merged